### ISSUE TITLE
Time to publish

### ISSUE THREAD

**Issue by Ballyglunin1** [rowenaryan/TetrisGame1#1]
Hey @rowenaryan how about we turn on GitHub and publish the game?

**Comment by rowenaryan** [comment]
Hey @Ballyglunin1 maybe we should review the project files and ensure we are good to go. Can you create an issue and complete this task please?

**Comment by rowenaryan** [comment]
GitHub pages turned on and the game is published at [gameURL](https://rowenaryan.github.io/TetrisGame1/)
